const placeUrlMapperObj = {
  "best-african-restaurants-in-alexandria-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/alexandria-new-south-wales-2015?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-alexandria-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/alexandria-new-south-wales-2015?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-carlingford-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/carlingford-new-south-wales-2118?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-café-in-carlingford-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/carlingford-new-south-wales-2118?businessTypes=café&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-cafe-restaurants-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?cuisines=cafe&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-mandi-restaurants-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?cuisines=mandi&page=1&productType=all&sort=LOCATION",
  "best-bars-pubs-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?businessTypes=bars_pubs&page=1&productType=all&sort=LOCATION",
  "best-beverages-in-marrickville-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/marrickville-new-south-wales-2204?businessTypes=beverages&page=1&productType=all&sort=LOCATION",
  "best-afghan-restaurants-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?cuisines=afghan&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-bar-in-north-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/north-sydney-new-south-wales-2060?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-rhodes-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/rhodes-new-south-wales-2138?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-bar-in-rhodes-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/rhodes-new-south-wales-2138?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-french-restaurants-in-surry-hills-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/surry-hills-new-south-wales-2010?cuisines=french&page=1&productType=all&sort=LOCATION",
  "best-food-truck-in-surry-hills-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/surry-hills-new-south-wales-2010?businessTypes=food_truck&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/sydney-new-south-wales-2000?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-sydney-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/sydney-new-south-wales-2000?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-cafe-restaurants-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?cuisines=cafe&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-croatian-restaurants-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?cuisines=croatian&page=1&productType=all&sort=LOCATION",
  "best-bars-pubs-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?businessTypes=bars_pubs&page=1&productType=all&sort=LOCATION",
  "best-beverages-in-yagoona-new-south-wales":
    "https://dev11.portal.kravein.com.au/places/yagoona-new-south-wales-2199?businessTypes=beverages&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-brisbane-city-queensland":
    "https://dev11.portal.kravein.com.au/places/brisbane-city-queensland-4000?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-brisbane-city-queensland":
    "https://dev11.portal.kravein.com.au/places/brisbane-city-queensland-4000?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-arabic-restaurants-in-cleveland-queensland":
    "https://dev11.portal.kravein.com.au/places/cleveland-queensland-4163?cuisines=arabic&page=1&productType=all&sort=LOCATION",
  "best-bar-in-cleveland-queensland":
    "https://dev11.portal.kravein.com.au/places/cleveland-queensland-4163?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-mackay-queensland":
    "https://dev11.portal.kravein.com.au/places/mackay-queensland-4740?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-street-food-restaurants-in-mackay-queensland":
    "https://dev11.portal.kravein.com.au/places/mackay-queensland-4740?cuisines=street_food&page=1&productType=all&sort=LOCATION",
  "best-food-truck-in-mackay-queensland":
    "https://dev11.portal.kravein.com.au/places/mackay-queensland-4740?businessTypes=food_truck&page=1&productType=all&sort=LOCATION",
  "best-afghan-restaurants-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?cuisines=afghan&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-arabic-restaurants-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?cuisines=arabic&page=1&productType=all&sort=LOCATION",
  "best-bar-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-murarrie-queensland":
    "https://dev11.portal.kravein.com.au/places/murarrie-queensland-4172?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-arabic-restaurants-in-adelaide-south-australia":
    "https://dev11.portal.kravein.com.au/places/adelaide-south-australia-5000?cuisines=arabic&page=1&productType=all&sort=LOCATION",
  "best-argentinean-restaurants-in-adelaide-south-australia":
    "https://dev11.portal.kravein.com.au/places/adelaide-south-australia-5000?cuisines=argentinean&page=1&productType=all&sort=LOCATION",
  "best-yunnan-restaurants-in-adelaide-south-australia":
    "https://dev11.portal.kravein.com.au/places/adelaide-south-australia-5000?cuisines=yunnan&page=1&productType=all&sort=LOCATION",
  "best-cabarets-in-adelaide-south-australia":
    "https://dev11.portal.kravein.com.au/places/adelaide-south-australia-5000?businessTypes=cabarets&page=1&productType=all&sort=LOCATION",
  "best-bistros-in-adelaide-south-australia":
    "https://dev11.portal.kravein.com.au/places/adelaide-south-australia-5000?businessTypes=bistros&page=1&productType=all&sort=LOCATION",
  "best-argentinean-restaurants-in-rowella-tasmania":
    "https://dev11.portal.kravein.com.au/places/rowella-tasmania-7270?cuisines=argentinean&page=1&productType=all&sort=LOCATION",
  "best-armenian-restaurants-in-rowella-tasmania":
    "https://dev11.portal.kravein.com.au/places/rowella-tasmania-7270?cuisines=armenian&page=1&productType=all&sort=LOCATION",
  "best-afghan-restaurants-in-rowella-tasmania":
    "https://dev11.portal.kravein.com.au/places/rowella-tasmania-7270?cuisines=afghan&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-rowella-tasmania":
    "https://dev11.portal.kravein.com.au/places/rowella-tasmania-7270?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-beverage-outlet-in-rowella-tasmania":
    "https://dev11.portal.kravein.com.au/places/rowella-tasmania-7270?businessTypes=beverage_outlet&page=1&productType=all&sort=LOCATION",
  "best-asian-fusion-restaurants-in-albert-park-victoria":
    "https://dev11.portal.kravein.com.au/places/albert-park-victoria-3206?cuisines=asian_fusion&page=1&productType=all&sort=LOCATION",
  "best-thai-restaurants-in-albert-park-victoria":
    "https://dev11.portal.kravein.com.au/places/albert-park-victoria-3206?cuisines=thai&page=1&productType=all&sort=LOCATION",
  "best-café-in-albert-park-victoria":
    "https://dev11.portal.kravein.com.au/places/albert-park-victoria-3206?businessTypes=café&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-albert-park-victoria":
    "https://dev11.portal.kravein.com.au/places/albert-park-victoria-3206?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-japanese-restaurants-in-alphington-victoria":
    "https://dev11.portal.kravein.com.au/places/alphington-victoria-3078?cuisines=japanese&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-alphington-victoria":
    "https://dev11.portal.kravein.com.au/places/alphington-victoria-3078?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-alphington-victoria":
    "https://dev11.portal.kravein.com.au/places/alphington-victoria-3078?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-alphington-victoria":
    "https://dev11.portal.kravein.com.au/places/alphington-victoria-3078?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-altona-victoria":
    "https://dev11.portal.kravein.com.au/places/altona-victoria-3018?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-altona-victoria":
    "https://dev11.portal.kravein.com.au/places/altona-victoria-3018?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-altona-victoria":
    "https://dev11.portal.kravein.com.au/places/altona-victoria-3018?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-altona-victoria":
    "https://dev11.portal.kravein.com.au/places/altona-victoria-3018?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-ashburton-victoria":
    "https://dev11.portal.kravein.com.au/places/ashburton-victoria-3147?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-armenian-restaurants-in-ashburton-victoria":
    "https://dev11.portal.kravein.com.au/places/ashburton-victoria-3147?cuisines=armenian&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-ashburton-victoria":
    "https://dev11.portal.kravein.com.au/places/ashburton-victoria-3147?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-café-in-ashburton-victoria":
    "https://dev11.portal.kravein.com.au/places/ashburton-victoria-3147?businessTypes=café&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-avondale-heights-victoria":
    "https://dev11.portal.kravein.com.au/places/avondale-heights-victoria-3034?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-avondale-heights-victoria":
    "https://dev11.portal.kravein.com.au/places/avondale-heights-victoria-3034?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-avondale-heights-victoria":
    "https://dev11.portal.kravein.com.au/places/avondale-heights-victoria-3034?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-burger-restaurants-in-bakery-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/bakery-hill-victoria-3350?cuisines=burger&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-bakery-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/bakery-hill-victoria-3350?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-food-truck-in-bakery-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/bakery-hill-victoria-3350?businessTypes=food_truck&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-balaclava-victoria":
    "https://dev11.portal.kravein.com.au/places/balaclava-victoria-3183?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-balaclava-victoria":
    "https://dev11.portal.kravein.com.au/places/balaclava-victoria-3183?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-beer-garden-in-balaclava-victoria":
    "https://dev11.portal.kravein.com.au/places/balaclava-victoria-3183?businessTypes=beer_garden&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-balwyn-north-victoria":
    "https://dev11.portal.kravein.com.au/places/balwyn-north-victoria-3104?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-balwyn-north-victoria":
    "https://dev11.portal.kravein.com.au/places/balwyn-north-victoria-3104?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-balwyn-north-victoria":
    "https://dev11.portal.kravein.com.au/places/balwyn-north-victoria-3104?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-balwyn-north-victoria":
    "https://dev11.portal.kravein.com.au/places/balwyn-north-victoria-3104?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-beaconsfield-victoria":
    "https://dev11.portal.kravein.com.au/places/beaconsfield-victoria-3807?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-beaconsfield-victoria":
    "https://dev11.portal.kravein.com.au/places/beaconsfield-victoria-3807?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-beaconsfield-victoria":
    "https://dev11.portal.kravein.com.au/places/beaconsfield-victoria-3807?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-belmont-victoria":
    "https://dev11.portal.kravein.com.au/places/belmont-victoria-3216?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-belmont-victoria":
    "https://dev11.portal.kravein.com.au/places/belmont-victoria-3216?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-café-in-belmont-victoria":
    "https://dev11.portal.kravein.com.au/places/belmont-victoria-3216?businessTypes=café&page=1&productType=all&sort=LOCATION",
  "best-fish-and-chips-restaurants-in-blackburn-victoria":
    "https://dev11.portal.kravein.com.au/places/blackburn-victoria-3130?cuisines=fish_and_chips&page=1&productType=all&sort=LOCATION",
  "best-food-court-in-blackburn-victoria":
    "https://dev11.portal.kravein.com.au/places/blackburn-victoria-3130?businessTypes=food_court&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-box-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/box-hill-victoria-3128?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-box-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/box-hill-victoria-3128?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-indian-restaurants-in-braybrook-victoria":
    "https://dev11.portal.kravein.com.au/places/braybrook-victoria-3019?cuisines=indian&page=1&productType=all&sort=LOCATION",
  "best-indonesian-restaurants-in-braybrook-victoria":
    "https://dev11.portal.kravein.com.au/places/braybrook-victoria-3019?cuisines=indonesian&page=1&productType=all&sort=LOCATION",
  "best-middle-eastern-restaurants-in-braybrook-victoria":
    "https://dev11.portal.kravein.com.au/places/braybrook-victoria-3019?cuisines=middle_eastern&page=1&productType=all&sort=LOCATION",
  "best-food-truck-in-braybrook-victoria":
    "https://dev11.portal.kravein.com.au/places/braybrook-victoria-3019?businessTypes=food_truck&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-brighton-victoria":
    "https://dev11.portal.kravein.com.au/places/brighton-victoria-3186?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-brighton-victoria":
    "https://dev11.portal.kravein.com.au/places/brighton-victoria-3186?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-brighton-victoria":
    "https://dev11.portal.kravein.com.au/places/brighton-victoria-3186?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-brewery-in-brighton-victoria":
    "https://dev11.portal.kravein.com.au/places/brighton-victoria-3186?businessTypes=brewery&page=1&productType=all&sort=LOCATION",
  "best-bakery-restaurants-in-bundoora-victoria":
    "https://dev11.portal.kravein.com.au/places/bundoora-victoria-3083?cuisines=bakery&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-bundoora-victoria":
    "https://dev11.portal.kravein.com.au/places/bundoora-victoria-3083?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-bundoora-victoria":
    "https://dev11.portal.kravein.com.au/places/bundoora-victoria-3083?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-capel-sound-victoria":
    "https://dev11.portal.kravein.com.au/places/capel-sound-victoria-3940?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-thai-restaurants-in-capel-sound-victoria":
    "https://dev11.portal.kravein.com.au/places/capel-sound-victoria-3940?cuisines=thai&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-capel-sound-victoria":
    "https://dev11.portal.kravein.com.au/places/capel-sound-victoria-3940?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-indian-restaurants-in-caulfield-south-victoria":
    "https://dev11.portal.kravein.com.au/places/caulfield-south-victoria-3162?cuisines=indian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-caulfield-south-victoria":
    "https://dev11.portal.kravein.com.au/places/caulfield-south-victoria-3162?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-cheltenham-victoria":
    "https://dev11.portal.kravein.com.au/places/cheltenham-victoria-3192?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-cheltenham-victoria":
    "https://dev11.portal.kravein.com.au/places/cheltenham-victoria-3192?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-cheltenham-victoria":
    "https://dev11.portal.kravein.com.au/places/cheltenham-victoria-3192?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-bar-food-restaurants-in-clarendon-victoria":
    "https://dev11.portal.kravein.com.au/places/clarendon-victoria-3352?cuisines=bar_food&page=1&productType=all&sort=LOCATION",
  "best-bar-in-clarendon-victoria":
    "https://dev11.portal.kravein.com.au/places/clarendon-victoria-3352?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-international-restaurants-in-clayton-victoria":
    "https://dev11.portal.kravein.com.au/places/clayton-victoria-3168?cuisines=international&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-clayton-victoria":
    "https://dev11.portal.kravein.com.au/places/clayton-victoria-3168?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-clayton-victoria":
    "https://dev11.portal.kravein.com.au/places/clayton-victoria-3168?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-clayton-victoria":
    "https://dev11.portal.kravein.com.au/places/clayton-victoria-3168?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-bakery-restaurants-in-coolaroo-victoria":
    "https://dev11.portal.kravein.com.au/places/coolaroo-victoria-3048?cuisines=bakery&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-coolaroo-victoria":
    "https://dev11.portal.kravein.com.au/places/coolaroo-victoria-3048?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-craigieburn-victoria":
    "https://dev11.portal.kravein.com.au/places/craigieburn-victoria-3064?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-craigieburn-victoria":
    "https://dev11.portal.kravein.com.au/places/craigieburn-victoria-3064?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-craigieburn-victoria":
    "https://dev11.portal.kravein.com.au/places/craigieburn-victoria-3064?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-pacific-restaurants-in-cranbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/cranbourne-victoria-3977?cuisines=pacific&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-cranbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/cranbourne-victoria-3977?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-cranbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/cranbourne-victoria-3977?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-cranbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/cranbourne-victoria-3977?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-croydon-victoria":
    "https://dev11.portal.kravein.com.au/places/croydon-victoria-3136?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-croydon-victoria":
    "https://dev11.portal.kravein.com.au/places/croydon-victoria-3136?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-croydon-victoria":
    "https://dev11.portal.kravein.com.au/places/croydon-victoria-3136?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-dandenong-victoria":
    "https://dev11.portal.kravein.com.au/places/dandenong-victoria-3175?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-dandenong-victoria":
    "https://dev11.portal.kravein.com.au/places/dandenong-victoria-3175?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-dandenong-victoria":
    "https://dev11.portal.kravein.com.au/places/dandenong-victoria-3175?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-cafe-restaurants-in-docklands-victoria":
    "https://dev11.portal.kravein.com.au/places/docklands-victoria-3008?cuisines=cafe&page=1&productType=all&sort=LOCATION",
  "best-beer-gardens-in-docklands-victoria":
    "https://dev11.portal.kravein.com.au/places/docklands-victoria-3008?businessTypes=beer_gardens&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-drysdale-victoria":
    "https://dev11.portal.kravein.com.au/places/drysdale-victoria-3222?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-drysdale-victoria":
    "https://dev11.portal.kravein.com.au/places/drysdale-victoria-3222?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-japanese-restaurants-in-east-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/east-melbourne-victoria-3002?cuisines=japanese&page=1&productType=all&sort=LOCATION",
  "best-sushi-restaurants-in-east-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/east-melbourne-victoria-3002?cuisines=sushi&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-east-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/east-melbourne-victoria-3002?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-east-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/east-melbourne-victoria-3002?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-elsternwick-victoria":
    "https://dev11.portal.kravein.com.au/places/elsternwick-victoria-3185?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-elsternwick-victoria":
    "https://dev11.portal.kravein.com.au/places/elsternwick-victoria-3185?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-café-in-elsternwick-victoria":
    "https://dev11.portal.kravein.com.au/places/elsternwick-victoria-3185?businessTypes=café&page=1&productType=all&sort=LOCATION",
  "best-deli-in-elsternwick-victoria":
    "https://dev11.portal.kravein.com.au/places/elsternwick-victoria-3185?businessTypes=deli&page=1&productType=all&sort=LOCATION",
  "best-fish-and-chips-restaurants-in-eltham-victoria":
    "https://dev11.portal.kravein.com.au/places/eltham-victoria-3095?cuisines=fish_and_chips&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-eltham-victoria":
    "https://dev11.portal.kravein.com.au/places/eltham-victoria-3095?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-eltham-victoria":
    "https://dev11.portal.kravein.com.au/places/eltham-victoria-3095?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-indian-restaurants-in-epping-victoria":
    "https://dev11.portal.kravein.com.au/places/epping-victoria-3076?cuisines=indian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-epping-victoria":
    "https://dev11.portal.kravein.com.au/places/epping-victoria-3076?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-venues-event-spaces-in-epping-victoria":
    "https://dev11.portal.kravein.com.au/places/epping-victoria-3076?businessTypes=venues_event_spaces&page=1&productType=all&sort=LOCATION",
  "best-bakery-restaurants-in-essendon-victoria":
    "https://dev11.portal.kravein.com.au/places/essendon-victoria-3040?cuisines=bakery&page=1&productType=all&sort=LOCATION",
  "best-sandwich-restaurants-in-essendon-victoria":
    "https://dev11.portal.kravein.com.au/places/essendon-victoria-3040?cuisines=sandwich&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-essendon-victoria":
    "https://dev11.portal.kravein.com.au/places/essendon-victoria-3040?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-vietnamese-restaurants-in-ferntree-gully-victoria":
    "https://dev11.portal.kravein.com.au/places/ferntree-gully-victoria-3156?cuisines=vietnamese&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-ferntree-gully-victoria":
    "https://dev11.portal.kravein.com.au/places/ferntree-gully-victoria-3156?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-ferntree-gully-victoria":
    "https://dev11.portal.kravein.com.au/places/ferntree-gully-victoria-3156?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-asian-fusion-restaurants-in-fitzroy-victoria":
    "https://dev11.portal.kravein.com.au/places/fitzroy-victoria-3065?cuisines=asian_fusion&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-fitzroy-victoria":
    "https://dev11.portal.kravein.com.au/places/fitzroy-victoria-3065?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-austrian-restaurants-in-fitzroy-victoria":
    "https://dev11.portal.kravein.com.au/places/fitzroy-victoria-3065?cuisines=austrian&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-fitzroy-victoria":
    "https://dev11.portal.kravein.com.au/places/fitzroy-victoria-3065?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-bistros-in-fitzroy-victoria":
    "https://dev11.portal.kravein.com.au/places/fitzroy-victoria-3065?businessTypes=bistros&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-forest-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/forest-hill-victoria-3131?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-forest-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/forest-hill-victoria-3131?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-forest-hill-victoria":
    "https://dev11.portal.kravein.com.au/places/forest-hill-victoria-3131?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-frankston-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-victoria-3199?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-frankston-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-victoria-3199?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-frankston-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-victoria-3199?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-frankston-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-victoria-3199?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-frankston-south-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-south-victoria-3199?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-frankston-south-victoria":
    "https://dev11.portal.kravein.com.au/places/frankston-south-victoria-3199?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-mexican-restaurants-in-geelong-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-victoria-3220?cuisines=mexican&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-geelong-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-victoria-3220?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-geelong-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-victoria-3220?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-geelong-west-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-west-victoria-3218?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-geelong-west-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-west-victoria-3218?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-geelong-west-victoria":
    "https://dev11.portal.kravein.com.au/places/geelong-west-victoria-3218?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-charcoal-chicken-restaurants-in-gladstone-park-victoria":
    "https://dev11.portal.kravein.com.au/places/gladstone-park-victoria-3043?cuisines=charcoal_chicken&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-gladstone-park-victoria":
    "https://dev11.portal.kravein.com.au/places/gladstone-park-victoria-3043?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-gladstone-park-victoria":
    "https://dev11.portal.kravein.com.au/places/gladstone-park-victoria-3043?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-kebab-restaurants-in-greensborough-victoria":
    "https://dev11.portal.kravein.com.au/places/greensborough-victoria-3088?cuisines=kebab&page=1&productType=all&sort=LOCATION",
  "best-food-truck-in-greensborough-victoria":
    "https://dev11.portal.kravein.com.au/places/greensborough-victoria-3088?businessTypes=food_truck&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-hampton-victoria":
    "https://dev11.portal.kravein.com.au/places/hampton-victoria-3188?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-hampton-victoria":
    "https://dev11.portal.kravein.com.au/places/hampton-victoria-3188?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-hurstbridge-victoria":
    "https://dev11.portal.kravein.com.au/places/hurstbridge-victoria-3099?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-hurstbridge-victoria":
    "https://dev11.portal.kravein.com.au/places/hurstbridge-victoria-3099?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-charcoal-chicken-restaurants-in-lalor-victoria":
    "https://dev11.portal.kravein.com.au/places/lalor-victoria-3075?cuisines=charcoal_chicken&page=1&productType=all&sort=LOCATION",
  "best-burger-restaurants-in-lalor-victoria":
    "https://dev11.portal.kravein.com.au/places/lalor-victoria-3075?cuisines=burger&page=1&productType=all&sort=LOCATION",
  "best-fast-food-restaurants-in-lalor-victoria":
    "https://dev11.portal.kravein.com.au/places/lalor-victoria-3075?cuisines=fast_food&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-lalor-victoria":
    "https://dev11.portal.kravein.com.au/places/lalor-victoria-3075?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-lalor-victoria":
    "https://dev11.portal.kravein.com.au/places/lalor-victoria-3075?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-japanese-restaurants-in-lucas-victoria":
    "https://dev11.portal.kravein.com.au/places/lucas-victoria-3350?cuisines=japanese&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-lucas-victoria":
    "https://dev11.portal.kravein.com.au/places/lucas-victoria-3350?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-malvern-victoria":
    "https://dev11.portal.kravein.com.au/places/malvern-victoria-3144?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-american-restaurants-in-malvern-victoria":
    "https://dev11.portal.kravein.com.au/places/malvern-victoria-3144?cuisines=american&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-malvern-victoria":
    "https://dev11.portal.kravein.com.au/places/malvern-victoria-3144?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-malvern-victoria":
    "https://dev11.portal.kravein.com.au/places/malvern-victoria-3144?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-malvern-victoria":
    "https://dev11.portal.kravein.com.au/places/malvern-victoria-3144?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/melbourne-victoria-3000?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/melbourne-victoria-3000?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/melbourne-victoria-3000?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-moorabbin-victoria":
    "https://dev11.portal.kravein.com.au/places/moorabbin-victoria-3189?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-moorabbin-victoria":
    "https://dev11.portal.kravein.com.au/places/moorabbin-victoria-3189?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-moorabbin-victoria":
    "https://dev11.portal.kravein.com.au/places/moorabbin-victoria-3189?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-mornington-victoria":
    "https://dev11.portal.kravein.com.au/places/mornington-victoria-3931?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-mornington-victoria":
    "https://dev11.portal.kravein.com.au/places/mornington-victoria-3931?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-mount-eliza-victoria":
    "https://dev11.portal.kravein.com.au/places/mount-eliza-victoria-3930?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-cafe-in-mount-eliza-victoria":
    "https://dev11.portal.kravein.com.au/places/mount-eliza-victoria-3930?businessTypes=cafe&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-newtown-victoria":
    "https://dev11.portal.kravein.com.au/places/newtown-victoria-3220?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-arabic-restaurants-in-newtown-victoria":
    "https://dev11.portal.kravein.com.au/places/newtown-victoria-3220?cuisines=arabic&page=1&productType=all&sort=LOCATION",
  "best-argentinean-restaurants-in-newtown-victoria":
    "https://dev11.portal.kravein.com.au/places/newtown-victoria-3220?cuisines=argentinean&page=1&productType=all&sort=LOCATION",
  "best-bar-in-newtown-victoria":
    "https://dev11.portal.kravein.com.au/places/newtown-victoria-3220?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-newtown-victoria":
    "https://dev11.portal.kravein.com.au/places/newtown-victoria-3220?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-fast-food-restaurants-in-ocean-grove-victoria":
    "https://dev11.portal.kravein.com.au/places/ocean-grove-victoria-3226?cuisines=fast_food&page=1&productType=all&sort=LOCATION",
  "best-fish-and-chips-restaurants-in-ocean-grove-victoria":
    "https://dev11.portal.kravein.com.au/places/ocean-grove-victoria-3226?cuisines=fish_and_chips&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-ocean-grove-victoria":
    "https://dev11.portal.kravein.com.au/places/ocean-grove-victoria-3226?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-ocean-grove-victoria":
    "https://dev11.portal.kravein.com.au/places/ocean-grove-victoria-3226?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-prahran-victoria":
    "https://dev11.portal.kravein.com.au/places/prahran-victoria-3181?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-prahran-victoria":
    "https://dev11.portal.kravein.com.au/places/prahran-victoria-3181?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-prahran-victoria":
    "https://dev11.portal.kravein.com.au/places/prahran-victoria-3181?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-prahran-victoria":
    "https://dev11.portal.kravein.com.au/places/prahran-victoria-3181?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-preston-victoria":
    "https://dev11.portal.kravein.com.au/places/preston-victoria-3072?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-bistros-in-preston-victoria":
    "https://dev11.portal.kravein.com.au/places/preston-victoria-3072?businessTypes=bistros&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-richmond-victoria":
    "https://dev11.portal.kravein.com.au/places/richmond-victoria-3121?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-richmond-victoria":
    "https://dev11.portal.kravein.com.au/places/richmond-victoria-3121?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-bar-in-richmond-victoria":
    "https://dev11.portal.kravein.com.au/places/richmond-victoria-3121?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-ringwood-victoria":
    "https://dev11.portal.kravein.com.au/places/ringwood-victoria-3134?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-ringwood-victoria":
    "https://dev11.portal.kravein.com.au/places/ringwood-victoria-3134?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-ringwood-victoria":
    "https://dev11.portal.kravein.com.au/places/ringwood-victoria-3134?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-ripponlea-victoria":
    "https://dev11.portal.kravein.com.au/places/ripponlea-victoria-3185?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-bar-in-ripponlea-victoria":
    "https://dev11.portal.kravein.com.au/places/ripponlea-victoria-3185?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-pub-food-restaurants-in-rosebud-victoria":
    "https://dev11.portal.kravein.com.au/places/rosebud-victoria-3939?cuisines=pub_food&page=1&productType=all&sort=LOCATION",
  "best-pub-in-rosebud-victoria":
    "https://dev11.portal.kravein.com.au/places/rosebud-victoria-3939?businessTypes=pub&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-rye-victoria":
    "https://dev11.portal.kravein.com.au/places/rye-victoria-3941?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-thai-restaurants-in-rye-victoria":
    "https://dev11.portal.kravein.com.au/places/rye-victoria-3941?cuisines=thai&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-rye-victoria":
    "https://dev11.portal.kravein.com.au/places/rye-victoria-3941?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-modern-australian-restaurants-in-seville-victoria":
    "https://dev11.portal.kravein.com.au/places/seville-victoria-3139?cuisines=modern_australian&page=1&productType=all&sort=LOCATION",
  "best-winery-in-seville-victoria":
    "https://dev11.portal.kravein.com.au/places/seville-victoria-3139?businessTypes=winery&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-south-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/south-melbourne-victoria-3205?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-south-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/south-melbourne-victoria-3205?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-south-wharf-victoria":
    "https://dev11.portal.kravein.com.au/places/south-wharf-victoria-3006?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-cafe-food-restaurants-in-south-wharf-victoria":
    "https://dev11.portal.kravein.com.au/places/south-wharf-victoria-3006?cuisines=cafe_food&page=1&productType=all&sort=LOCATION",
  "best-food-court-in-south-wharf-victoria":
    "https://dev11.portal.kravein.com.au/places/south-wharf-victoria-3006?businessTypes=food_court&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-south-yarra-victoria":
    "https://dev11.portal.kravein.com.au/places/south-yarra-victoria-3141?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-south-yarra-victoria":
    "https://dev11.portal.kravein.com.au/places/south-yarra-victoria-3141?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-arabic-restaurants-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?cuisines=arabic&page=1&productType=all&sort=LOCATION",
  "best-afghan-restaurants-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?cuisines=afghan&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-bakery-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?businessTypes=bakery&page=1&productType=all&sort=LOCATION",
  "best-bar-in-southbank-victoria":
    "https://dev11.portal.kravein.com.au/places/southbank-victoria-3006?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-springvale-south-victoria":
    "https://dev11.portal.kravein.com.au/places/springvale-south-victoria-3172?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-fast-food-restaurants-in-springvale-south-victoria":
    "https://dev11.portal.kravein.com.au/places/springvale-south-victoria-3172?cuisines=fast_food&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-springvale-south-victoria":
    "https://dev11.portal.kravein.com.au/places/springvale-south-victoria-3172?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-springvale-south-victoria":
    "https://dev11.portal.kravein.com.au/places/springvale-south-victoria-3172?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-vietnamese-restaurants-in-st-albans-victoria":
    "https://dev11.portal.kravein.com.au/places/st-albans-victoria-3021?cuisines=vietnamese&page=1&productType=all&sort=LOCATION",
  "best-pho-restaurants-in-st-albans-victoria":
    "https://dev11.portal.kravein.com.au/places/st-albans-victoria-3021?cuisines=pho&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-st-albans-victoria":
    "https://dev11.portal.kravein.com.au/places/st-albans-victoria-3021?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-st-kilda-victoria":
    "https://dev11.portal.kravein.com.au/places/st-kilda-victoria-3182?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-st-kilda-victoria":
    "https://dev11.portal.kravein.com.au/places/st-kilda-victoria-3182?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-pub-food-restaurants-in-st-kilda-east-victoria":
    "https://dev11.portal.kravein.com.au/places/st-kilda-east-victoria-3183?cuisines=pub_food&page=1&productType=all&sort=LOCATION",
  "best-pub-in-st-kilda-east-victoria":
    "https://dev11.portal.kravein.com.au/places/st-kilda-east-victoria-3183?businessTypes=pub&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-sunbury-victoria":
    "https://dev11.portal.kravein.com.au/places/sunbury-victoria-3429?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-sunbury-victoria":
    "https://dev11.portal.kravein.com.au/places/sunbury-victoria-3429?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-sunbury-victoria":
    "https://dev11.portal.kravein.com.au/places/sunbury-victoria-3429?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-argentinean-restaurants-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?cuisines=argentinean&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-brewery-in-tarneit-victoria":
    "https://dev11.portal.kravein.com.au/places/tarneit-victoria-3029?businessTypes=brewery&page=1&productType=all&sort=LOCATION",
  "best-indian-restaurants-in-thomastown-victoria":
    "https://dev11.portal.kravein.com.au/places/thomastown-victoria-3074?cuisines=indian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-thomastown-victoria":
    "https://dev11.portal.kravein.com.au/places/thomastown-victoria-3074?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-tapas-restaurants-in-torquay-victoria":
    "https://dev11.portal.kravein.com.au/places/torquay-victoria-3228?cuisines=tapas&page=1&productType=all&sort=LOCATION",
  "best-bar-in-torquay-victoria":
    "https://dev11.portal.kravein.com.au/places/torquay-victoria-3228?businessTypes=bar&page=1&productType=all&sort=LOCATION",
  "best-chinese-restaurants-in-vermont-south-victoria":
    "https://dev11.portal.kravein.com.au/places/vermont-south-victoria-3133?cuisines=chinese&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-vermont-south-victoria":
    "https://dev11.portal.kravein.com.au/places/vermont-south-victoria-3133?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-coffee-and-tea-restaurants-in-wantirna-victoria":
    "https://dev11.portal.kravein.com.au/places/wantirna-victoria-3152?cuisines=coffee_and_tea&page=1&productType=all&sort=LOCATION",
  "best-desserts-restaurants-in-wantirna-victoria":
    "https://dev11.portal.kravein.com.au/places/wantirna-victoria-3152?cuisines=desserts&page=1&productType=all&sort=LOCATION",
  "best-dessert-parlour-in-wantirna-victoria":
    "https://dev11.portal.kravein.com.au/places/wantirna-victoria-3152?businessTypes=dessert_parlour&page=1&productType=all&sort=LOCATION",
  "best-yunnan-restaurants-in-waurn-ponds-victoria":
    "https://dev11.portal.kravein.com.au/places/waurn-ponds-victoria-3216?cuisines=yunnan&page=1&productType=all&sort=LOCATION",
  "best-xinjiang-restaurants-in-waurn-ponds-victoria":
    "https://dev11.portal.kravein.com.au/places/waurn-ponds-victoria-3216?cuisines=xinjiang&page=1&productType=all&sort=LOCATION",
  "best-winery-in-waurn-ponds-victoria":
    "https://dev11.portal.kravein.com.au/places/waurn-ponds-victoria-3216?businessTypes=winery&page=1&productType=all&sort=LOCATION",
  "best-african-restaurants-in-werribee-victoria":
    "https://dev11.portal.kravein.com.au/places/werribee-victoria-3030?cuisines=african&page=1&productType=all&sort=LOCATION",
  "best-albanian-restaurants-in-werribee-victoria":
    "https://dev11.portal.kravein.com.au/places/werribee-victoria-3030?cuisines=albanian&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-werribee-victoria":
    "https://dev11.portal.kravein.com.au/places/werribee-victoria-3030?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-beer-garden-in-werribee-victoria":
    "https://dev11.portal.kravein.com.au/places/werribee-victoria-3030?businessTypes=beer_garden&page=1&productType=all&sort=LOCATION",
  "best-italian-restaurants-in-west-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/west-melbourne-victoria-3003?cuisines=italian&page=1&productType=all&sort=LOCATION",
  "best-bed-and-breakfast-b-b-in-west-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/west-melbourne-victoria-3003?businessTypes=bed_and_breakfast_b_b&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-west-melbourne-victoria":
    "https://dev11.portal.kravein.com.au/places/west-melbourne-victoria-3003?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-asian-restaurants-in-white-hills-victoria":
    "https://dev11.portal.kravein.com.au/places/white-hills-victoria-3550?cuisines=asian&page=1&productType=all&sort=LOCATION",
  "best-asian-fusion-restaurants-in-white-hills-victoria":
    "https://dev11.portal.kravein.com.au/places/white-hills-victoria-3550?cuisines=asian_fusion&page=1&productType=all&sort=LOCATION",
  "best-bistros-in-white-hills-victoria":
    "https://dev11.portal.kravein.com.au/places/white-hills-victoria-3550?businessTypes=bistros&page=1&productType=all&sort=LOCATION",
  "best-bars-pubs-in-white-hills-victoria":
    "https://dev11.portal.kravein.com.au/places/white-hills-victoria-3550?businessTypes=bars_pubs&page=1&productType=all&sort=LOCATION",
  "best-kebab-restaurants-in-windsor-victoria":
    "https://dev11.portal.kravein.com.au/places/windsor-victoria-3181?cuisines=kebab&page=1&productType=all&sort=LOCATION",
  "best-pizza-restaurants-in-windsor-victoria":
    "https://dev11.portal.kravein.com.au/places/windsor-victoria-3181?cuisines=pizza&page=1&productType=all&sort=LOCATION",
  "best-takeaway-in-windsor-victoria":
    "https://dev11.portal.kravein.com.au/places/windsor-victoria-3181?businessTypes=takeaway&page=1&productType=all&sort=LOCATION",
  "best-fast-food-in-windsor-victoria":
    "https://dev11.portal.kravein.com.au/places/windsor-victoria-3181?businessTypes=fast_food&page=1&productType=all&sort=LOCATION",
  "best-indian-restaurants-in-wodonga-victoria":
    "https://dev11.portal.kravein.com.au/places/wodonga-victoria-3690?cuisines=indian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-wodonga-victoria":
    "https://dev11.portal.kravein.com.au/places/wodonga-victoria-3690?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-contemporary-restaurants-in-yarraville-victoria":
    "https://dev11.portal.kravein.com.au/places/yarraville-victoria-3013?cuisines=contemporary&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-yarraville-victoria":
    "https://dev11.portal.kravein.com.au/places/yarraville-victoria-3013?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-restaurant-in-yarraville-victoria":
    "https://dev11.portal.kravein.com.au/places/yarraville-victoria-3013?businessTypes=restaurant&page=1&productType=all&sort=LOCATION",
  "best-australian-restaurants-in-south-perth-western-australia":
    "https://dev11.portal.kravein.com.au/places/south-perth-western-australia-6151?cuisines=australian&page=1&productType=all&sort=LOCATION",
  "best-cabarets-in-south-perth-western-australia":
    "https://dev11.portal.kravein.com.au/places/south-perth-western-australia-6151?businessTypes=cabarets&page=1&productType=all&sort=LOCATION",
};

export default placeUrlMapperObj;
